Add config for TFChain WebSocket in ctor 2
threefoldtech/rmb-sdk-ts pull request #32
Opened 2023-03-07 15:41 UTC by MohamedElmdary

2023-03-07 16:41 UTC, AhmedHanafy725 requested changes

2023-03-07 16:41 UTC, AhmedHanafy725 commented on lib/client.ts
> +import type { WebSocket as WSConnection } from "ws";
is this working on the browser? `ws` package is a nodejs package

2023-03-07 16:41 UTC, AhmedHanafy725 commented on lib/client.ts
> +              c.close();
why creating `c` here, it's already this.con?

2023-03-07 16:41 UTC, AhmedHanafy725 commented on lib/client.ts
> +        this.api?.off("disconnected", this.__handleConnection);
I think we should remove the event handler before calling the disconnect method

2023-03-08 08:23 UTC, MohamedElmdary commented on lib/client.ts
> +import type { WebSocket as WSConnection } from "ws";
it's `import type` will be removed in compile time

2023-03-08 08:23 UTC, MohamedElmdary commented on lib/client.ts
> +              c.close();
To assign a type for it as it's marked as `never` for some reason

2023-03-08 08:25 UTC, AhmedHanafy725 approved these changes

2023-03-08 08:29 UTC, merged