Support ping pong
threefoldtech/rmb-sdk-ts pull request #34
Opened 2023-03-13 08:50 UTC by MohamedElmdary

2023-03-16 11:05 UTC, amiraabouhadid requested changes

2023-03-16 11:05 UTC, amiraabouhadid commented on lib/client.ts
> +            });
i don't see where you keep sending ping every 20s and where you reconnect if no pong is received after 40s

2023-03-16 11:05 UTC, amiraabouhadid commented on lib/client.ts
> +                    resolve(envelope.pong)
needs to retry reading for pong for 40s if no pong is received

2023-03-16 12:00 UTC, MohamedElmdary commented on lib/client.ts
> +                    resolve(envelope.pong)
Currently if no pong is received within 40s it should recall ping method again

2023-03-16 13:01 UTC, amiraabouhadid requested changes

2023-03-16 13:01 UTC, amiraabouhadid commented on lib/client.ts
> +                this.__pingPongTimeout = setTimeout(() => {
shouldn't this be setInterval? setTimout is executed only once, we want it executing every 20 seconds

2023-03-16 13:01 UTC, amiraabouhadid commented on lib/client.ts
> +                    resolve(envelope.pong)
I don't see the 40 s anywhere, where is it please

2023-03-21 12:15 UTC, amiraabouhadid approved these changes

2023-03-21 12:17 UTC, merged